/**
 * The output store for a directory this build does not own alone.
 *
 * A NUXT PUBLIC DIRECTORY HAS TWO WRITERS AND ONLY ONE OF THEM IS THIS ONE. Nitro assembles its
 * own application there, and the reference is written into a mount under it. Where the two agree
 * on a path, whichever writes last wins and nothing says so, which is the failure SPEC 16.1
 * already refuses for two page addresses that fold to one file. So a write onto a path this
 * build did not put there is a refusal that names both the file and the fact, rather than an
 * overwrite.
 *
 * WHAT IS NOT A COLLISION: THIS BUILD'S OWN PREVIOUS OUTPUT. The incremental path of SPEC 16.3
 * exists to rewrite the files a previous build wrote, and the manifest is what says which those
 * are, so the previous manifest's file list is passed in and those paths are the build's own.
 *
 * AND THE NITRO PROXY ROUTE IS NOT PUBLISHED, WHICH IS THE ONE FILE HELD BACK. SPEC 16.2's Nitro
 * artefact is server source, and server source inside a public directory is source a reader can
 * fetch. Under Nuxt the same generated bytes become a registered route instead, so the store
 * takes the file, records it and does not write it. The two are held equal by
 * `nitro-proxy.spec.ts` and by `nuxt-parity.spec.ts`, since a file that is quietly dropped and a
 * file that is quietly wrong look the same from here.
 */

import { ErrorCode, InvalidOptionsError } from '@openref/core';
import { FsOutputStore, type IOutputStore } from '@openref/static';
import { lstat, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

/** What the guarded store needs to know about the directory it is writing into. */
export interface PublicDirStoreOptions {
  /** Absolute path of the public directory, which is the deployment root. */
  readonly root: string;
  /** Path under the root the reference is written to, `docs` for a base of `/docs`. */
  readonly mount: string;
  /** Files the previous build of this reference wrote, from its own manifest. */
  readonly ownedFiles: readonly string[];
  /** File whose contents become a route instead of a published file, or null. */
  readonly withheldFile: string | null;
}

/** Writes a reference into a directory another builder also writes into. */
export class PublicDirStore implements IOutputStore {
  private readonly inner: IOutputStore;
  private readonly root: string;
  private readonly mount: string;
  private readonly owned: Set<string>;
  private readonly withheldFile: string | null;

  /** Contents of the withheld file, once the build has offered it. */
  private withheldContent: string | null = null;

  /** Whether the mount directory has already been proven to be a directory in this build. */
  private mountVerified = false;

  /** @param options - Where it writes and what it may overwrite */
  constructor(options: PublicDirStoreOptions) {
    this.root = options.root;
    this.mount = options.mount;
    this.owned = new Set(options.ownedFiles);
    this.withheldFile = options.withheldFile;
    this.inner = new FsOutputStore(join(options.root, options.mount));
  }

  /** The generated server source the build offered and this store did not publish. */
  get withheld(): string | null {
    return this.withheldContent;
  }

  /** @inheritdoc */
  read(path: string): Promise<string | null> {
    return this.inner.read(path);
  }

  /** @inheritdoc */
  async write(path: string, contents: string): Promise<void> {
    if (path === this.withheldFile) {
      this.withheldContent = contents;
      return;
    }

    await this.verifyMount();
    await this.refuseForeign(path);
    await this.inner.write(path, contents);
    this.owned.add(path);
  }

  /** @inheritdoc */
  async writeBytes(path: string, bytes: Uint8Array): Promise<void> {
    await this.verifyMount();
    await this.refuseForeign(path);
    await this.inner.writeBytes(path, bytes);
    this.owned.add(path);
  }

  /** @inheritdoc */
  remove(path: string): Promise<void> {
    this.owned.delete(path);
    return this.inner.remove(path);
  }

  /**
   * Verifies the mount directory itself, once, before anything is written under it.
   *
   * THE ONE PATH THE INNER STORE DOES NOT CHECK IS ITS OWN ROOT, AND UNDER NUXT THAT ROOT IS NOT
   * THE DEPLOYER'S WORD. `FsOutputStore` verifies every directory inside the root and deliberately
   * follows the root itself, because for `openref build --out` the root is what the flag asked
   * for. Here the root is `<publicDir>/<mount>`: only `publicDir` is the deployment's, and the
   * mount segments are computed from `base`. `T062` measured both halves of the hole. A symbolic
   * link at `public/docs`, which is an ordinary thing for a repository to commit, carried the
   * whole reference outside the public directory while every other check said the paths were
   * inside; a plain file at the same place produced a raw `EEXIST: file already exists, mkdir`
   * from underneath, in a store whose entire purpose is a refusal that names the file and the
   * fact.
   *
   * THE SEGMENTS ARE WALKED, NOT JUST THE LAST ONE, because a mount of `/docs/v1` has two of them
   * and a link at either carries the same write to the same place.
   *
   * @throws {InvalidOptionsError} When a mount segment is a link or is not a directory
   */
  private async verifyMount(): Promise<void> {
    if (this.mountVerified) return;

    // THE PUBLIC DIRECTORY ITSELF IS NITRO'S AND IS TREATED THE WAY `FsOutputStore` TREATS ITS OWN
    // ROOT: created if absent, followed if it is a link, because it is the deployment's own word.
    await mkdir(this.root, { recursive: true });

    let current = this.root;
    for (const segment of this.mount.split('/').filter((part) => part !== '')) {
      current = join(current, segment);

      const entry = await lstat(current).catch(() => null);
      if (entry === null) {
        await mkdir(current);
        continue;
      }

      if (entry.isSymbolicLink() || !entry.isDirectory()) {
        throw new InvalidOptionsError(
          `openref: ${current} is ${entry.isSymbolicLink() ? 'a symbolic link' : 'not a directory'}, and it is where the reference would be written. A build never follows a link out of the directory it was given, and it never writes the reference over somebody else's file. Mount the reference at a path of its own, or remove that entry`,
          ErrorCode.CONFIG_INVALID_OPTIONS,
          undefined,
          { mount: this.mount, root: this.root, entry: current },
        );
      }
    }

    this.mountVerified = true;
  }

  /**
   * Refuses a path that already holds something this build did not put there.
   *
   * @param path - Path relative to the mount, forward slashes
   * @throws {InvalidOptionsError} When the file exists and belongs to another writer
   */
  private async refuseForeign(path: string): Promise<void> {
    if (this.owned.has(path)) return;

    const absolute = join(this.root, this.mount, path);
    try {
      await lstat(absolute);
    } catch {
      return;
    }

    throw new InvalidOptionsError(
      `openref: ${join(this.mount, path)} already exists in the Nuxt public directory and no openref build wrote it, so publishing the reference here would overwrite somebody else's file. Mount the reference at a path of its own, or remove that file`,
      ErrorCode.CONFIG_INVALID_OPTIONS,
      undefined,
      { file: path, mount: this.mount, root: this.root },
    );
  }
}
