/**
 * The output store for a directory this build does not own alone.
 *
 * A NUXT PUBLIC DIRECTORY HAS TWO WRITERS AND ONLY ONE OF THEM IS THIS ONE. Nitro assembles its
 * own application there, and the reference is written into a mount under it. Where the two agree
 * on a path, whichever writes last wins and nothing says so, which is the failure SPEC 16.1
 * already refuses for two page addresses that fold to one file. So a write onto a path this
 * build did not put there is a refusal that names both the file and the fact, rather than an
 * overwrite.
 *
 * WHAT IS NOT A COLLISION: THIS BUILD'S OWN PREVIOUS OUTPUT. The incremental path of SPEC 16.3
 * exists to rewrite the files a previous build wrote, and the manifest is what says which those
 * are, so the previous manifest's file list is passed in and those paths are the build's own.
 *
 * AND THE NITRO PROXY ROUTE IS NOT PUBLISHED, WHICH IS THE ONE FILE HELD BACK. SPEC 16.2's Nitro
 * artefact is server source, and server source inside a public directory is source a reader can
 * fetch. Under Nuxt the same generated bytes become a registered route instead, so the store
 * takes the file, records it and does not write it. The two are held equal by
 * `nitro-proxy.spec.ts` and by `nuxt-parity.spec.ts`, since a file that is quietly dropped and a
 * file that is quietly wrong look the same from here.
 */

import { ErrorCode, InvalidOptionsError } from '@openref/core';
import { FsOutputStore, type IOutputStore } from '@openref/static';
import { lstat } from 'node:fs/promises';
import { join } from 'node:path';

/** What the guarded store needs to know about the directory it is writing into. */
export interface PublicDirStoreOptions {
  /** Absolute path of the public directory, which is the deployment root. */
  readonly root: string;
  /** Path under the root the reference is written to, `docs` for a base of `/docs`. */
  readonly mount: string;
  /** Files the previous build of this reference wrote, from its own manifest. */
  readonly ownedFiles: readonly string[];
  /** File whose contents become a route instead of a published file, or null. */
  readonly withheldFile: string | null;
}

/** Writes a reference into a directory another builder also writes into. */
export class PublicDirStore implements IOutputStore {
  private readonly inner: IOutputStore;
  private readonly root: string;
  private readonly mount: string;
  private readonly owned: Set<string>;
  private readonly withheldFile: string | null;

  /** Contents of the withheld file, once the build has offered it. */
  private withheldContent: string | null = null;

  /** @param options - Where it writes and what it may overwrite */
  constructor(options: PublicDirStoreOptions) {
    this.root = options.root;
    this.mount = options.mount;
    this.owned = new Set(options.ownedFiles);
    this.withheldFile = options.withheldFile;
    this.inner = new FsOutputStore(join(options.root, options.mount));
  }

  /** The generated server source the build offered and this store did not publish. */
  get withheld(): string | null {
    return this.withheldContent;
  }

  /** @inheritdoc */
  read(path: string): Promise<string | null> {
    return this.inner.read(path);
  }

  /** @inheritdoc */
  async write(path: string, contents: string): Promise<void> {
    if (path === this.withheldFile) {
      this.withheldContent = contents;
      return;
    }

    await this.refuseForeign(path);
    await this.inner.write(path, contents);
    this.owned.add(path);
  }

  /** @inheritdoc */
  async writeBytes(path: string, bytes: Uint8Array): Promise<void> {
    await this.refuseForeign(path);
    await this.inner.writeBytes(path, bytes);
    this.owned.add(path);
  }

  /** @inheritdoc */
  remove(path: string): Promise<void> {
    this.owned.delete(path);
    return this.inner.remove(path);
  }

  /**
   * Refuses a path that already holds something this build did not put there.
   *
   * @param path - Path relative to the mount, forward slashes
   * @throws {InvalidOptionsError} When the file exists and belongs to another writer
   */
  private async refuseForeign(path: string): Promise<void> {
    if (this.owned.has(path)) return;

    const absolute = join(this.root, this.mount, path);
    try {
      await lstat(absolute);
    } catch {
      return;
    }

    throw new InvalidOptionsError(
      `openref: ${join(this.mount, path)} already exists in the Nuxt public directory and no openref build wrote it, so publishing the reference here would overwrite somebody else's file. Mount the reference at a path of its own, or remove that file`,
      ErrorCode.CONFIG_INVALID_OPTIONS,
      undefined,
      { file: path, mount: this.mount, root: this.root },
    );
  }
}
