import { describe, expect, it } from 'vitest';
import {
  buildHealthReport,
  healthScore,
  healthScoreMark,
  healthSuppressionNote,
  type IRDocument,
  type IRHealthCheck,
  type IRNode,
  type IROperation,
  type IRSchema,
} from '../../src/index';

/**
 * Host side suppression of finding classes, per SPEC 7.2.
 *
 * SUPPRESSION IS A MOVE AND NOT A DELETION, which is the property every case below rests on. A
 * suppressed finding leaves `drift` and arrives in `suppression.findings` of the same report, so
 * every counter that recomputes a length follows for free and the two halves add back up to the
 * whole with no stored total that could disagree with them.
 *
 * THE SCORE IS THE PRIMARY NUMBER AND NOT THE FLATTERING ONE. While any suppressed class is
 * severity `error` the report leads with the UNSUPPRESSED figure, so a host cannot buy a headline
 * by suppressing `security-drift`. That inversion is what the last three cases are about.
 */

/** The bare operation the fixtures start from. */
function operation(overrides: Partial<IROperation> = {}): IROperation {
  return {
    kind: 'operation',
    id: 'get-orders',
    method: 'get',
    path: '/orders',
    operationId: 'get-orders',
    tags: [],
    deprecated: false,
    parameters: [],
    responses: [],
    security: [],
    servers: [],
    ...overrides,
  };
}

/** A document holding the given nodes and schemas, in the order they were passed. */
function documentOf(nodes: readonly IRNode[], schemas: readonly IRSchema[] = []): IRDocument {
  return {
    id: 'orders',
    kind: 'http',
    hash: '',
    info: { title: 'Orders', version: '1.0.0' },
    servers: [],
    navigation: [],
    nodes: new Map(nodes.map((node) => [node.id, node])),
    schemas: new Map(schemas.map((schema) => [schema.id, schema])),
    security: [],
    relationships: [],
    webhooks: new Map(),
  };
}

/** A 200 response carrying a body, with or without a written example. */
function ok(withExample: boolean): IROperation['responses'][number] {
  return {
    statusCode: '200',
    description: 'ok',
    content: [
      {
        mediaType: 'application/json',
        schema: {
          kind: 'inline',
          schema: { id: 'body', dialect: 'json-schema-2020-12', normalized: { type: 'object' } },
        },
        ...(withExample ? { examples: { default: { value: { id: 1 } } } } : {}),
      },
    ],
    headers: [],
  };
}

/** Three operations, none of which carries a summary, an example or a hand written id. */
function threeUndocumented(): IRDocument {
  return documentOf([
    operation({ id: 'a', path: '/a', responses: [ok(false)] }),
    operation({ id: 'b', path: '/b', responses: [ok(false)] }),
    operation({ id: 'c', path: '/c', responses: [ok(false)] }),
  ]);
}

describe('buildHealthReport with runtime.suppress', () => {
  it('should move a suppressed class out of drift rather than delete it', () => {
    // Given a document whose findings include one class the host decided not to fix
    const document = threeUndocumented();
    const before = buildHealthReport(document);
    const examples = before.drift.filter((issue) => issue.rule === 'missing-example');

    // When that class is suppressed with a reason
    const after = buildHealthReport(document, {
      suppress: [{ rule: 'missing-example', reason: 'examples are generated by the client SDK' }],
    });

    // Then the findings LEFT `drift` AND ARRIVED in the second array of the same report, so the
    // two halves add back up to the whole and nothing had to store the total.
    expect(examples.length).toBeGreaterThan(0);
    expect(after.drift.some((issue) => issue.rule === 'missing-example')).toBe(false);
    expect(after.suppression?.findings).toEqual(examples);
    expect(after.drift.length + (after.suppression?.findings.length ?? 0)).toBe(
      before.drift.length,
    );
  });

  it('should express suppression by subtracting from the check rather than removing it', () => {
    // Given a document where one operation carries an example and two do not, so the check is
    // partly answered rather than answered not at all
    const document = documentOf([
      operation({ id: 'a', path: '/a', responses: [ok(false)] }),
      operation({ id: 'b', path: '/b', responses: [ok(false)] }),
      operation({ id: 'c', path: '/c', responses: [ok(true)] }),
    ]);
    const before = buildHealthReport(document);
    const beforeCheck = before.checks.find((check) => check.id === 'missing-example');

    // When
    const after = buildHealthReport(document, {
      suppress: [{ rule: 'missing-example', reason: 'examples are generated by the client SDK' }],
    });
    const afterCheck = after.checks.find((check) => check.id === 'missing-example');

    // Then the subjects that failed left the question and the ones that passed stayed, which is
    // what generalises to a node level suppression later without the check vanishing.
    expect(beforeCheck).toEqual({
      id: 'missing-example',
      label: 'Operations with an example',
      passed: 1,
      total: 3,
      severity: 'info',
    });
    expect(afterCheck).toEqual({
      id: 'missing-example',
      label: 'Operations with an example',
      passed: 1,
      total: 1,
      severity: 'info',
    });
  });

  it('should record a class that matched nothing rather than dropping it', () => {
    // Given a document with no streaming endpoint at all, so the suppressed class is empty here
    const document = threeUndocumented();

    // When
    const report = buildHealthReport(document, {
      suppress: [{ rule: 'stream-unspecified', reason: 'streams are documented in the wiki' }],
    });

    // Then it is carried with `matched: 0`, because a class legitimately empty on one deployment
    // is a class that starts suppressing silently on the day it comes back.
    expect(report.suppression?.classes).toEqual([
      {
        rule: 'stream-unspecified',
        severity: 'error',
        reason: 'streams are documented in the wiki',
        matched: 0,
      },
    ]);
    expect(report.suppression?.findings).toEqual([]);
  });

  it('should leave the report untouched when nothing is suppressed', () => {
    // Given
    const document = threeUndocumented();

    // When
    const bare = buildHealthReport(document);
    const empty = buildHealthReport(document, { suppress: [] });

    // Then, byte for byte the report a host has today, and no member appears that a version 1
    // reader would have to know about.
    expect(empty).toEqual(bare);
    expect(bare.suppression).toBeUndefined();
    expect(healthScoreMark(bare)).toBe(`${String(bare.score)}%`);
    expect(healthSuppressionNote(bare)).toBe('');
  });

  it('should carry the score of what is reported when no suppressed class is an error', () => {
    // Given two quiet classes suppressed on a document that answers its other question, which is
    // the maintainer's case: the two he decided not to fix are the ones dragging the number
    const document = documentOf([
      operation({ id: 'a', path: '/a', summary: 'A', responses: [ok(false)] }),
      operation({ id: 'b', path: '/b', summary: 'B', responses: [ok(false)] }),
      operation({ id: 'c', path: '/c', summary: 'C', responses: [ok(false)] }),
    ]);
    const before = buildHealthReport(document);

    // When
    const after = buildHealthReport(document, {
      suppress: [
        { rule: 'missing-example', reason: 'generated by the client SDK' },
        { rule: 'missing-operation-id', reason: 'ids are generated and stable enough' },
      ],
    });

    // Then the primary is the suppressed score, the unsuppressed one rides beside it, and the
    // mark prints both with the primary first.
    expect(after.suppression?.inverted).toBe(false);
    expect(after.suppression?.unsuppressedScore).toBe(before.score);
    expect(after.score).toBe(after.suppression?.suppressedScore);
    expect(after.score).toBeGreaterThan(before.score);
    expect(healthScoreMark(after)).toBe(
      `${String(after.score)}% (${String(before.score)}% unsuppressed)`,
    );
  });

  it('should invert the headline while any suppressed class is an error', () => {
    // Given a document whose only complaint is an error class, which is the case a prohibition
    // would have removed the escape from and which the inversion answers instead
    const document = documentOf([
      operation({
        id: 'a',
        path: '/a',
        operationId: 'listOrders',
        rawOperationId: 'listOrders',
        summary: 'List orders',
        responses: [ok(true)],
        runtime: {
          guards: [
            { name: 'JwtAuthGuard', scope: 'route', confidence: 'declared', collector: 'guards' },
          ],
        },
      }),
    ]);
    const bare = buildHealthReport(document);

    // When the error class is suppressed
    const report = buildHealthReport(document, {
      suppress: [{ rule: 'security-drift', reason: 'authorisation is enforced by the gateway' }],
    });

    // Then the suppressed score IS 100 and it is NOT the primary. Suppressing a note buys a
    // cleaner list and a better headline; suppressing an error buys a cleaner list and no
    // headline improvement at all.
    expect(bare.drift.every((issue) => issue.rule === 'security-drift')).toBe(true);
    expect(report.suppression?.suppressedScore).toBe(100);
    expect(report.suppression?.inverted).toBe(true);
    expect(report.score).toBe(bare.score);
    expect(report.score).toBeLessThan(100);
    expect(healthScoreMark(report)).toBe(`${String(bare.score)}% (100% suppressed)`);
  });

  it('should invert on the loudest suppressed class and not on the last one named', () => {
    // Given one quiet class and one error class suppressed together, in that order
    const document = documentOf([
      operation({
        id: 'a',
        path: '/a',
        responses: [ok(false)],
        runtime: {
          guards: [
            { name: 'JwtAuthGuard', scope: 'route', confidence: 'declared', collector: 'guards' },
          ],
        },
      }),
    ]);

    // When
    const report = buildHealthReport(document, {
      suppress: [
        { rule: 'missing-example', reason: 'generated by the client SDK' },
        { rule: 'security-drift', reason: 'authorisation is enforced by the gateway' },
      ],
    });

    // Then one error anywhere in the set is enough, which is the whole of the rule.
    expect(report.suppression?.inverted).toBe(true);
    expect(report.suppression?.classes.map((entry) => entry.severity)).toEqual(['info', 'error']);
  });

  it('should say how many findings were suppressed and by how many classes', () => {
    // Given
    const document = threeUndocumented();

    // When
    const report = buildHealthReport(document, {
      suppress: [
        { rule: 'missing-example', reason: 'generated by the client SDK' },
        { rule: 'missing-operation-id', reason: 'ids are generated and stable enough' },
      ],
    });

    // Then the sentence is built once here and read everywhere, so no surface counts its own way
    expect(report.suppression?.findings).toHaveLength(6);
    expect(healthSuppressionNote(report)).toBe('6 suppressed by 2 classes');
  });

  it('should write one class in the singular', () => {
    // Given, because `1 suppressed by 1 classes` is the sort of string a reader stops trusting
    const report = buildHealthReport(
      documentOf([operation({ operationId: 'listOrders', rawOperationId: 'listOrders' })]),
      { suppress: [{ rule: 'missing-description', reason: 'summaries live in the handbook' }] },
    );

    // When
    const note = healthSuppressionNote(report);

    // Then
    expect(note).toBe('1 suppressed by 1 class');
  });

  it('should keep the suppressed findings in report order', () => {
    // Given a document whose findings interleave two rules across three subjects
    const document = threeUndocumented();
    const before = buildHealthReport(document);

    // When
    const after = buildHealthReport(document, {
      suppress: [{ rule: 'missing-description', reason: 'summaries live in the handbook' }],
    });

    // Then the moved list is the report's own order with the rest removed, so a disclosure reads
    // in the same order as the panel it hangs under.
    expect(after.suppression?.findings).toEqual(
      before.drift.filter((issue) => issue.rule === 'missing-description'),
    );
  });

  it('should hold the arithmetic the maintainer measured on his own application', () => {
    // Given the check profile of the maintainer's application, 58 operations and 180 findings, of
    // which 111 are the two classes he decided not to fix: DX030 at 58 and DX020 at 53
    const checks: readonly IRHealthCheck[] = [
      { id: 'missing-operation-id', label: 'ids', passed: 0, total: 58, severity: 'warning' },
      { id: 'missing-example', label: 'examples', passed: 5, total: 58, severity: 'info' },
      { id: 'missing-description', label: 'summaries', passed: 58, total: 58, severity: 'warning' },
      { id: 'security-drift', label: 'security', passed: 22, total: 26, severity: 'error' },
      { id: 'scope-drift', label: 'scopes', passed: 28, total: 29, severity: 'warning' },
      { id: 'stream-unspecified', label: 'streams', passed: 45, total: 52, severity: 'error' },
      { id: 'parameter-unread', label: 'parameters', passed: 45, total: 57, severity: 'warning' },
      {
        id: 'header-requiredness-drift',
        label: 'headers',
        passed: 23,
        total: 24,
        severity: 'warning',
      },
      { id: 'status-drift', label: 'statuses', passed: 53, total: 56, severity: 'error' },
      { id: 'dto-field-undescribed', label: 'fields', passed: 432, total: 466, severity: 'info' },
      { id: 'discovery-incomplete', label: 'discovery', passed: 0, total: 7, severity: 'warning' },
      { id: 'runtime-collectors', label: 'collectors', passed: 4, total: 5, severity: 'warning' },
    ];

    // When the two classes are subtracted, which is what suppression does to a check
    const suppressed = checks.map((check) => {
      if (check.id === 'missing-operation-id') return { ...check, passed: 0, total: 0 };
      if (check.id === 'missing-example') return { ...check, passed: 5, total: 5 };

      return check;
    });

    // Then his 77 becomes 88, which is the figure the option exists to move and the reason the
    // unsuppressed one has to keep being printed beside it.
    expect(healthScore(checks)).toBe(77);
    expect(healthScore(suppressed)).toBe(88);
  });
});
