/**
 * The Nuxt module of SPEC 16.4: two hooks, and neither of them renders anything itself.
 *
 * WHAT A WRAPPER MEANS HERE, STATED SO IT CAN BE CHECKED. `nitro:config` declares what answers
 * live and `nitro:build:public-assets` runs the static build; the pages, the assets, the
 * navigation, the search index, the sitemap, `llms.txt` and the proxy rules are produced by
 * `@openref/static` in both cases. This file decides where things are mounted and nothing about
 * what they contain.
 *
 * THE PRERENDERER IS TOLD TO STAY OUT OF THE MOUNT, AND THAT IS THE FORK THIS FILE EXISTS TO
 * PREVENT. Nitro's prerenderer crawls the links of the pages it renders, so an application page
 * that links the reference would have it walk every page of the reference and write those files
 * itself, out of the served path. Two writers of one address, whose bytes agree only by accident:
 * the reference is generated by the static build and by nothing else.
 *
 * NO TELEMETRY IS TOUCHED AND NONE IS ADDED. SPEC 19.5 puts telemetry at zero, and Nuxt's own is
 * the host's setting rather than this module's to change silently; the example application turns
 * it off in `nuxt.config` where a reader can see it, and `zero-outbound.spec.ts` is what proves
 * the build made no request.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildAssetCatalog, loadDefaultAssets, type AssetPlan } from '@openref/render';
import { ASSET_DIRECTORY as SITE_ASSET_SEGMENT } from '@openref/static';
import {
  generateSite,
  mountDirectoryOf,
} from '../../generate/application/services/generate-site.service';
import {
  loadSpecification,
  documentOf,
} from '../../document/application/services/load-specification.service';
import { nitroProxyRoute, nitroProxySource } from '../../proxy/domain/nitro-proxy-route';
import {
  generatesStatically,
  resolveNuxtOptions,
  type OpenRefNuxtOptions,
  type ResolvedNuxtOptions,
} from '../domain/module-options';
import type { EmbeddedSite } from '../../runtime/site';
import type {
  NitroConfigSurface,
  NitroSurface,
  NuxtModule,
  NuxtSurface,
} from '../../shared/types/nuxt-surface';

/**
 * Where the generated entries are written, relative to the Nuxt project root.
 *
 * TWO PLACES WERE TRIED FIRST AND BOTH FAILED FOR REASONS WORTH KEEPING, since the obvious homes
 * are the two that do not work. `.nuxt`, the build directory, is emptied after modules have run:
 * measured on Nuxt 4.5.2, where the bundler reported "could not be resolved, treating it as an
 * external dependency" and the prerenderer then failed on a path that no longer existed. Then
 * `node_modules/.cache`, the conventional home for generated build input, where the reference
 * entry resolved and the proxy route did not compile: SPEC 16.2's Nitro artefact is TypeScript,
 * `as const` and all, and Nitro's TypeScript transform does not reach inside `node_modules`, so
 * rollup parsed it as JavaScript and stopped at `Expected a semicolon`.
 *
 * SO IT IS A DIRECTORY OF THE PROJECT, BESIDE `.nuxt` AND NAMED LIKE IT. Generated input that a
 * transform has to see has to live where the transform looks, which is the project.
 */
export const GENERATED_DIRECTORY = '.openref';

/** The generated file that hands the runtime its embedded site. */
export const REFERENCE_ENTRY = 'reference-handler.ts';

/** Directory under {@link GENERATED_DIRECTORY} holding the assets a served mount publishes. */
export const GENERATED_ASSET_DIRECTORY = 'assets';

/** How long a hashed asset may be cached: it is addressed by its own digest. */
export const ASSET_MAX_AGE = 31_536_000;

/** The generated file holding SPEC 16.2's Nitro route, byte for byte as the CLI writes it. */
export const PROXY_ENTRY = 'proxy-route.ts';

/** Specifier the generated entry imports the runtime from. */
export const RUNTIME_SPECIFIER = '@openref/nuxt/runtime';

/**
 * The source of the generated entry that binds the runtime to one embedded site.
 *
 * THREE LINES AND A JSON LITERAL, deliberately. Everything a generated file carries is a thing
 * no test of this repository typechecks, so what is generated is the smallest possible statement
 * of "this reference, that runtime", and the runtime it calls is ordinary compiled code.
 *
 * @param embedded - What the server needs to build the site
 * @returns The file contents
 */
export function referenceEntrySource(embedded: EmbeddedSite): string {
  return [
    '// openref reference route, generated by the Nuxt module. Do not edit by hand.',
    `import { createReferenceHandler } from ${JSON.stringify(RUNTIME_SPECIFIER)};`,
    '',
    `export default createReferenceHandler(${JSON.stringify(embedded, null, 2)});`,
    '',
  ].join('\n');
}

/**
 * What the server build needs to answer for this reference.
 *
 * THE ASSETS ARRIVE AS NAMES AND NOT AS BYTES, and the reason is in `SiteAssetNames`: a hashed
 * asset is an immutable file, so a Nitro deployment answers it from its static layer, and what
 * the pages need is the served name each one resolved to. The bytes are written where Nitro
 * publishes them, by `publishAssets` below, from this same catalogue.
 *
 * @param options - The resolved options
 * @param specification - The document, already read
 * @param assets - The resolved default assets
 * @returns The embedded site
 */
function embeddedSiteOf(
  options: ResolvedNuxtOptions,
  specification: { readonly path: string; readonly text: string },
  assets: AssetPlan,
): EmbeddedSite {
  const catalog = buildAssetCatalog(assets.sources);

  return {
    specification: specification.text,
    source: specification.path,
    base: options.base,
    target: options.target ?? null,
    forwardCookies: options.forwardCookies,
    lang: options.lang ?? null,
    colorScheme: options.colorScheme ?? null,
    assets: {
      servedNames: Object.fromEntries(
        catalog.assets.map((asset) => [asset.name, asset.servedName]),
      ),
      stylesheetNames: assets.stylesheetNames,
      moduleName: assets.moduleName,
    },
  };
}

/**
 * Writes the assets a served mount publishes, under their served names.
 *
 * THE BYTES ARE THE CATALOGUE'S AND NOT THE FILES', which matters: `buildAssetCatalog` rewrites
 * the references between assets, so a stylesheet's `url()` and a chunk's import specifier point
 * at the hashed names. Copying the source files instead would publish a stylesheet asking for a
 * font that is not there under that name.
 *
 * @param assets - The resolved default assets
 * @param directory - Where to write them
 * @returns The served names written
 */
function publishAssets(assets: AssetPlan, directory: string): readonly string[] {
  mkdirSync(directory, { recursive: true });

  const written: string[] = [];
  for (const asset of buildAssetCatalog(assets.sources).assets) {
    writeFileSync(join(directory, asset.servedName), asset.bytes);
    written.push(asset.servedName);
  }

  return written;
}

/**
 * The module Nuxt calls.
 *
 * @param inlineOptions - Options written beside the module in `nuxt.config`
 * @param nuxt - The Nuxt instance
 */
async function openRefModule(
  inlineOptions: Partial<OpenRefNuxtOptions> | undefined,
  nuxt: NuxtSurface,
): Promise<void> {
  const configured = (nuxt.options.openref ?? {}) as Partial<OpenRefNuxtOptions>;
  const options = resolveNuxtOptions({ ...configured, ...inlineOptions });

  const specification = await loadSpecification(options.spec, nuxt.options.rootDir);
  const generatedDirectory = join(nuxt.options.rootDir, GENERATED_DIRECTORY);
  const notice = (message: string): void => {
    process.stderr.write(message);
  };

  // THE ENTRIES ARE WRITTEN INSIDE `nitro:config` AND NOT HERE, WHICH IS A FACT ABOUT NUXT AND
  // WAS MEASURED. Nuxt empties the build directory after modules have run, so a file written at
  // setup is gone by the time Nitro looks for it, and what Nitro reports is that the handler
  // could not be resolved and is therefore external, which then fails at prerender time with a
  // path that no longer exists. The hook runs after the directory has been prepared, and the
  // writes are synchronous because the hook is.
  const proxySource =
    options.target === 'nitro'
      ? nitroProxySource(
          documentOf(specification.text, specification.path),
          options.basePath,
          options.forwardCookies,
        )
      : null;

  // WHICH HALF RUNS IS DECIDED ONCE, IN THE FIRST HOOK, AND THE SECOND HOOK READS THE DECISION.
  // `nitro:config` is where the routes have to be declared and it is also the first place Nitro
  // says whether this build is static, so the answer is taken there and carried.
  let generating = false;

  nuxt.hook('nitro:config', (config: NitroConfigSurface) => {
    generating = generatesStatically(options.generate, config.static);

    mkdirSync(generatedDirectory, { recursive: true });

    config.handlers ??= [];

    if (!generating) {
      const assets = loadDefaultAssets({ resolveFrom: import.meta.url });
      const entry = join(generatedDirectory, REFERENCE_ENTRY);
      writeFileSync(
        entry,
        referenceEntrySource(embeddedSiteOf(options, specification, assets)),
        'utf8',
      );
      // TWO ROUTES AND THE FIRST ONE IS THE MOUNT ITSELF, which Nitro's catch all does not cover:
      // measured on Nitro 2.13.4, where `/docs/**` answered `/docs/get-parcels` and left `/docs`
      // to the application's own renderer, so the overview was the framework's 404 page. The
      // overview's address is the bare base, per `overviewHref`, so it is registered by name.
      config.handlers.push({ route: options.basePath, handler: entry, method: 'get' });
      config.handlers.push({ route: `${options.basePath}/**`, handler: entry, method: 'get' });

      const assetDirectory = join(generatedDirectory, GENERATED_ASSET_DIRECTORY);
      publishAssets(assets, assetDirectory);
      config.publicAssets ??= [];
      config.publicAssets.push({
        dir: assetDirectory,
        baseURL: `${options.basePath}/${SITE_ASSET_SEGMENT}`,
        maxAge: ASSET_MAX_AGE,
      });
    }

    // THE PROXY ROUTE IS THE GENERATOR'S FILE, WRITTEN WHERE NITRO CAN LOAD IT. Its bytes are
    // what `openref build --target nitro` writes, which is asserted rather than assumed.
    if (proxySource !== null) {
      const entry = join(generatedDirectory, PROXY_ENTRY);
      writeFileSync(entry, proxySource, 'utf8');
      config.handlers.push({ route: nitroProxyRoute(options.basePath), handler: entry });

      // A STATIC DEPLOYMENT HAS NO ROUTE TO ANSWER WITH, AND THE PAGES WOULD SAY IT DOES. The
      // built pages address `<base>/_proxy/u<N>`, which under `nuxt generate` nothing serves, so
      // the console would send a reader's request into a 404. Said out loud rather than left for
      // the reader to find, per the SPEC 16.2 rule that a degradation is named.
      if (generating) {
        notice(
          `openref: target "nitro" generates a static deployment here, and a static deployment runs no server, so the ${options.basePath}/_proxy rules the pages address will not answer. Build with a server preset, or pick a target the platform can rewrite\n`,
        );
      }
    }

    config.prerender ??= {};
    config.prerender.ignore ??= [];
    config.prerender.ignore.push(options.basePath);
  });

  nuxt.hook('nitro:build:public-assets', async (nitro: NitroSurface) => {
    if (!generating) return;

    await generateSite(options, specification, nitro.options.output.publicDir, notice);
  });
}

openRefModule.meta = {
  name: '@openref/nuxt',
  configKey: 'openref',
};

/** The module, as `nuxt.config` takes it. */
export const openRefNuxtModule: NuxtModule<OpenRefNuxtOptions> = openRefModule;

export { mountDirectoryOf };
